### ISSUE TITLE
Issues with PHP version on refactor branch

### ISSUE THREAD

**Issue by paltorg** [SYNQfm/SYNQ-WP#25]
![skjermbilde 2017-09-14 kl 10 39 30](https://user-images.githubusercontent.com/25321467/30420162-075c0388-9939-11e7-95f8-10464b829df6.png)

**Comment by jettlin** [comment]
@paltorg Do we have any more info on this?  Right now I'm not seeing any `curl` usage in the project but we do apparently use GuzzleHttp which may cause the issue (haven't investigated fully).  Not sure if this is still an issue either since I run a VVV environment with 7.0 installed and everything just works...

**Comment by jettlin** [comment]
Cannot reproduce issue
